ProTwo/urls.py
from django.contrib import admin
from django.urls import include, path
from appTwo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('appTwo/', include('appTwo.urls')),
    path('user_logout/', views.user_logout,name='user_logout'),

    path('', views.index,name='index'),
    path('welcome/', views.welcome,name='welcome'),

    path('user_login/', views.user_login,name='user_login'),



]

appTwo/urls.py
from django.urls import path

from . import views
app_name="appTwo"
urlpatterns = [
        path('', views.index, name='index'),

    path('appTwo/', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    






]

appTwo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

appTwo/forms.py
from django import forms
from django.contrib.auth.models import User
from appTwo.models import UserProfileInfo





class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('first_name','last_name','username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

appTwo/views.py
from django.shortcuts import render

# Create your views here.
#from appTwo.models import User

from appTwo.forms import  UserProfileInfoForm,UserForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import login,logout,authenticate

def index(request):
    return render(request,"appTwo/index.html")


@login_required
def special(request):
    return HttpResponse("You are logged in!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('user_login'))

@login_required
def welcome(request):
    return render(request,"appTwo/welcome.html")




def register(request):
    registered=False




    if request.method =="POST":
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user


            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

                profile.save()

            registered=True
        else:
              print(user_form.errors,profile_form.errors)







    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()



    return render(request,'appTwo/registerations.html',{"user_form":user_form,'profile_form':profile_form,'registered':registered})





def user_login(request):
    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:


            if user.is_active:

                login(request,user)

                return HttpResponseRedirect(reverse('welcome'))

            else:
               HttpResponse("Please register first")
        else:
            print("someone tried to login and failed")
            print("Username:{} and password {}".format(username,password))
            return HttpResponse("Invalid login details")

    else:
         return render(request,'appTwo/login.html',{})

templates/appTwo/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>My page</title>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">



<link rel="stylesheet" href="{% static 'css/index.css' %}">
  </head>
  <body>


    <nav class="navbar fixed-top navbar navbar-expand-lg navbar navbar-dark ">
      <div class="container" >
      <ul class="navbar-nav mr-auto">

          <li class="nav-item active"><a class="navbar-brand" href="{% url 'admin:index' %}"> Admin site </a>
          <li class="nav-item active"><a class="navbar-brand" href="{% url 'appTwo:index' %}">Homepage</a>
          <li class="nav-item active"><a class="navbar-brand" href="{% url 'appTwo:register' %}">Register</a>

             {% if user.is_authenticated %}
               <li class="nav-item active"><a class="navbar-brand" href="{% url 'user_logout' %}">Logout</a></li>
             {% else %}
               <li class="nav-item active"><a class="navbar-brand" href="{% url 'appTwo:user_login' %}">Login</a></li>
             {% endif %}







            </ul>
          </div>

          </nav>
          <br><br><br>
  <h1>Welcome to the page</h1>

<img src="{% static "flower.jpg" %}" alt="sorry">




  </body>
</html>

templates/appTwo/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">



<link rel="stylesheet" href="{% static 'css/index.css' %}">
  </head>
  <body>
    <nav class="navbar fixed-top navbar navbar-expand-lg navbar navbar-dark ">
      <div class="container" >
      <ul class="navbar-nav mr-auto">

          <li class="nav-item active"><a class="navbar-brand" href="{% url 'admin:index' %}"> Admin site </a>
              <li class="nav-item active"><a class="navbar-brand" href="{% url 'appTwo:index' %}">Homepage</a>
                  <li class="nav-item active"><a class="navbar-brand" href="{% url 'appTwo:register' %}">Register</a>
                    {% if user.is_authenticated %}
                       <li class="nav-item active"><a class="navbar-brand" href="{% url 'user_logout' %}">Logout</a></li>
                     {% else %}
                        <li class="nav-item active"><a class="navbar-brand" href="{% url 'appTwo:user_login' %}">Login</a><li>
                     {% endif %}








            </ul>
          </div>

          </nav>
          <br><br>

          <h1>PLEASE LOGIN</h1>
          <br>
          <form  action="{% url 'appTwo:user_login' %}" method="post">
              {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" >
            <label for="password">Password:</label>
            <input type="password" name="password" >
            <input type="submit" name="" value="Login">



          </form>


  </body>
</html>

templates/appTwo/registerations.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Register</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/registerations.css' %}">
  </head>
  <body>
    <nav class="navbar fixed-top navbar navbar-expand-lg navbar navbar-dark ">
      <div class="container" >
      <ul class="navbar-nav mr-auto">

          <li class="nav-item active"><a class="navbar-brand" href="{% url  'admin:index' %}"> Admin site </a>
              <li class="nav-item active"><a class="navbar-brand" href="{% url 'appTwo:index' %}">Homepage</a>
                  <li class="nav-item active"><a class="navbar-brand" href="{% url 'appTwo:register' %}">Register</a>
                    {% if user.is_authenticated %}
                       <li class="nav-item active"><a class="navbar-brand" href="{% url 'user_logout' %}">Logout</a></li>
                     {% else %}
                        <li class="nav-item active"><a class="navbar-brand" href="{% url 'appTwo:user_login' %}">Login</a><li>
                     {% endif %}









            </ul>
          </div>

          </nav>
          <br><br><br>

          <div class="cimp">
             {% if registered %}
                <h1 id="simp">Thank you for registering!</h1>
             {% else %}
                <h1>PLEASE FILL UP THE FORM TO REGISTER</h1>
                 <form  enctype="multipart/form-data "method="post">
                    {% csrf_token%}
                  <b>{{user_form.as_p}}</b>
                  <b>{{profile_form.as_p}}</b>
                  <input type="submit"  value="Register">
                  </form>
             {% endif %}

          </div>


  </body>
</html>

templates/appTwo/welcome.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Welcome</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/registerations.css' %}">
  </head>
  <body>
    <nav class="navbar fixed-top navbar navbar-expand-lg navbar navbar-dark ">
      <div class="container" >
      <ul class="navbar-nav mr-auto">

          <li class="nav-item active"><a class="navbar-brand" href="{% url  'admin:index' %}"> Admin site </a>
              <li class="nav-item active"><a class="navbar-brand" href="{% url 'appTwo:index' %}">Homepage</a>
                  <li class="nav-item active"><a class="navbar-brand" href="{% url 'appTwo:register' %}">Register</a>
                    <br><br>
                    {% if user.is_authenticated %}
                       <li class="nav-item active"><a class="navbar-brand" href="{% url 'user_logout' %}">Logout</a></li>
                     {% else %}
                        <li class="nav-item active"><a class="navbar-brand" href="{% url 'appTwo:user_login' %}">Login</a><li>
                     {% endif %}

                   </ul>
                 </div>

                 </nav>
                 <br><br><br>

    <h1>Welcome to your page</h1>
  </body>
</html>